# Generated by Django 3.2.20 on 2023-12-31 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_community_post',
            field=models.BooleanField(default=False),
        ),
    ]
