# Generated by Django 3.2.20 on 2024-01-03 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_is_community_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_community_post',
        ),
    ]
