# Generated by Django 3.2.20 on 2023-08-30 16:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_auto_20230817_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={},
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='communities_joined', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='communities_moderated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('hidden', 'Hidden')], default='public', max_length=20),
        ),
    ]
