# Generated by Django 3.2.20 on 2023-11-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_communitypost'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='moderators_usernames',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='community',
            name='owner_username',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
