# Generated by Django 3.2.20 on 2023-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invites', '0002_invitation_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
